#!/bin/bash
#
# Receive messages from Android app

file_name=$1
shift

while [[ $w != "" ]]; do
  case $1 in
    -p|--path)
      local_path=$2
    shift 2
    ;;
  esac
done  

adb pull ./sdcard/Android/data/com.google.firebase.messaging.testing.fcmexternalprobertarget/files/$local_path$file_name
cat $file_name
rm $file_name
