#!/bin/bash
#
# Receive messages from Android app

android_path=./sdcard/Android/data/com.google.firebase.messaging.testing.fcmexternalprobertarget/files/

file_name=$1
shift

while [[ $1 != "" ]]; do
  case $1 in
    -p|--path)
      local_path=$2
    shift 2
    ;;
  esac
done  

if adb shell [[ ! -f $android_path$local_path$file_name ]]; then
  echo nf
else
  adb pull $android_path$local_path$file_name > /dev/null
  cat $file_name
  rm $file_name
fi
