#!/bin/bash
#
# Send messages to FCM 

send_time=""
device=""
auth=""

while [[ $1 != "" ]]; do
  case $1 in
    -t|--time)
      send_time=$2
      shift 2
      ;;
    -d|--device)
      device=$2
      shift 2
      ;;
    -a|--auth)
      auth=$2
      shift 2
      ;;
  esac
done

message="\"data\":{\"sendTime\": \"$send_time\"},\"token\":\"$device\""

# Build cURL command
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $auth" \
-d "{\"message\": {$message}}" \
https://fcm.googleapis.com/v1/projects/gifted-cooler-279818/messages:send
