// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: controller.proto

package controller

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProbeType int32

const (
	ProbeType_UNSPECIFIED      ProbeType = 0
	ProbeType_ONCE_PER_INSTALL ProbeType = 1
	ProbeType_TOPIC            ProbeType = 2
)

// Enum value maps for ProbeType.
var (
	ProbeType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ONCE_PER_INSTALL",
		2: "TOPIC",
	}
	ProbeType_value = map[string]int32{
		"UNSPECIFIED":      0,
		"ONCE_PER_INSTALL": 1,
		"TOPIC":            2,
	}
)

func (x ProbeType) Enum() *ProbeType {
	p := new(ProbeType)
	*p = x
	return p
}

func (x ProbeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_proto_enumTypes[0].Descriptor()
}

func (ProbeType) Type() protoreflect.EnumType {
	return &file_controller_proto_enumTypes[0]
}

func (x ProbeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProbeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProbeType(num)
	return nil
}

// Deprecated: Use ProbeType.Descriptor instead.
func (ProbeType) EnumDescriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

type ControllerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probes         *ProbeConfigs `protobuf:"bytes,1,opt,name=probes" json:"probes,omitempty"`
	MinCpu         *string       `protobuf:"bytes,2,req,name=min_cpu,json=minCpu,def=Intel Haswell" json:"min_cpu,omitempty"`
	DiskImageName  *string       `protobuf:"bytes,3,req,name=disk_image_name,json=diskImageName,def=probe_disk" json:"disk_image_name,omitempty"`
	ServiceAccount *string       `protobuf:"bytes,4,req,name=service_account,json=serviceAccount,def=send-service-account@gifted-cooler-279818.iam.gserviceaccount.com" json:"service_account,omitempty"`
}

// Default values for ControllerConfig fields.
const (
	Default_ControllerConfig_MinCpu         = string("Intel Haswell")
	Default_ControllerConfig_DiskImageName  = string("probe_disk")
	Default_ControllerConfig_ServiceAccount = string("send-service-account@gifted-cooler-279818.iam.gserviceaccount.com")
)

func (x *ControllerConfig) Reset() {
	*x = ControllerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerConfig) ProtoMessage() {}

func (x *ControllerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerConfig.ProtoReflect.Descriptor instead.
func (*ControllerConfig) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ControllerConfig) GetProbes() *ProbeConfigs {
	if x != nil {
		return x.Probes
	}
	return nil
}

func (x *ControllerConfig) GetMinCpu() string {
	if x != nil && x.MinCpu != nil {
		return *x.MinCpu
	}
	return Default_ControllerConfig_MinCpu
}

func (x *ControllerConfig) GetDiskImageName() string {
	if x != nil && x.DiskImageName != nil {
		return *x.DiskImageName
	}
	return Default_ControllerConfig_DiskImageName
}

func (x *ControllerConfig) GetServiceAccount() string {
	if x != nil && x.ServiceAccount != nil {
		return *x.ServiceAccount
	}
	return Default_ControllerConfig_ServiceAccount
}

type ProbeConfigs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probe []*ProbeConfig `protobuf:"bytes,1,rep,name=probe" json:"probe,omitempty"`
}

func (x *ProbeConfigs) Reset() {
	*x = ProbeConfigs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfigs) ProtoMessage() {}

func (x *ProbeConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfigs.ProtoReflect.Descriptor instead.
func (*ProbeConfigs) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeConfigs) GetProbe() []*ProbeConfig {
	if x != nil {
		return x.Probe
	}
	return nil
}

type ProbeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region         *string    `protobuf:"bytes,1,req,name=region,def=us-central1" json:"region,omitempty"`
	Type           *ProbeType `protobuf:"varint,2,req,name=type,enum=ProbeType,def=0" json:"type,omitempty"`
	SendNumber     *int32     `protobuf:"varint,3,req,name=send_number,json=sendNumber,def=10" json:"send_number,omitempty"`
	SendInterval   *int32     `protobuf:"varint,4,req,name=send_interval,json=sendInterval,def=10" json:"send_interval,omitempty"`
	ReceiveTimeout *int32     `protobuf:"varint,5,req,name=receive_timeout,json=receiveTimeout,def=20" json:"receive_timeout,omitempty"`
}

// Default values for ProbeConfig fields.
const (
	Default_ProbeConfig_Region         = string("us-central1")
	Default_ProbeConfig_Type           = ProbeType_UNSPECIFIED
	Default_ProbeConfig_SendNumber     = int32(10)
	Default_ProbeConfig_SendInterval   = int32(10)
	Default_ProbeConfig_ReceiveTimeout = int32(20)
)

func (x *ProbeConfig) Reset() {
	*x = ProbeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfig) ProtoMessage() {}

func (x *ProbeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfig.ProtoReflect.Descriptor instead.
func (*ProbeConfig) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeConfig) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return Default_ProbeConfig_Region
}

func (x *ProbeConfig) GetType() ProbeType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_ProbeConfig_Type
}

func (x *ProbeConfig) GetSendNumber() int32 {
	if x != nil && x.SendNumber != nil {
		return *x.SendNumber
	}
	return Default_ProbeConfig_SendNumber
}

func (x *ProbeConfig) GetSendInterval() int32 {
	if x != nil && x.SendInterval != nil {
		return *x.SendInterval
	}
	return Default_ProbeConfig_SendInterval
}

func (x *ProbeConfig) GetReceiveTimeout() int32 {
	if x != nil && x.ReceiveTimeout != nil {
		return *x.ReceiveTimeout
	}
	return Default_ProbeConfig_ReceiveTimeout
}

var File_controller_proto protoreflect.FileDescriptor

var file_controller_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x12, 0x26,
	0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x3a,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x20, 0x48, 0x61, 0x73, 0x77, 0x65, 0x6c, 0x6c, 0x52, 0x06,
	0x6d, 0x69, 0x6e, 0x43, 0x70, 0x75, 0x12, 0x32, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x3a,
	0x0a, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x52, 0x0d, 0x64, 0x69, 0x73,
	0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x6a, 0x0a, 0x0f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x09, 0x3a, 0x41, 0x73, 0x65, 0x6e, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x40, 0x67, 0x69, 0x66, 0x74, 0x65, 0x64,
	0x2d, 0x63, 0x6f, 0x6f, 0x6c, 0x65, 0x72, 0x2d, 0x32, 0x37, 0x39, 0x38, 0x31, 0x38, 0x2e, 0x69,
	0x61, 0x6d, 0x2e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x22, 0xda, 0x01, 0x0a, 0x0b, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x3a, 0x0b, 0x75, 0x73, 0x2d, 0x63,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x31, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0b,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x05, 0x3a, 0x02, 0x31, 0x30, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x27, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x3a, 0x02, 0x31, 0x30, 0x52, 0x0c, 0x73, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x2b, 0x0a, 0x0f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20,
	0x02, 0x28, 0x05, 0x3a, 0x02, 0x32, 0x30, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x2a, 0x3d, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x4e, 0x43, 0x45, 0x5f, 0x50, 0x45,
	0x52, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54,
	0x4f, 0x50, 0x49, 0x43, 0x10, 0x02,
}

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData = file_controller_proto_rawDesc
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_proto_rawDescData)
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_controller_proto_goTypes = []interface{}{
	(ProbeType)(0),           // 0: ProbeType
	(*ControllerConfig)(nil), // 1: ControllerConfig
	(*ProbeConfigs)(nil),     // 2: ProbeConfigs
	(*ProbeConfig)(nil),      // 3: ProbeConfig
}
var file_controller_proto_depIdxs = []int32{
	2, // 0: ControllerConfig.probes:type_name -> ProbeConfigs
	3, // 1: ProbeConfigs.probe:type_name -> ProbeConfig
	0, // 2: ProbeConfig.type:type_name -> ProbeType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeConfigs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		EnumInfos:         file_controller_proto_enumTypes,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_rawDesc = nil
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
